// <auto-generated />
using Enterprise.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Enterprise.Persistence.Migrations
{
    [DbContext(typeof(EnterpriseContext))]
    partial class EnterpriseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("Enterprise.Domain.Depto", b =>
                {
                    b.Property<int>("DeptoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sigla")
                        .HasColumnType("TEXT");

                    b.HasKey("DeptoId");

                    b.ToTable("Deptos");

                    b.HasData(
                        new
                        {
                            DeptoId = 1,
                            Nome = "Venda",
                            Sigla = "VEN"
                        },
                        new
                        {
                            DeptoId = 2,
                            Nome = "Recurso Humanos",
                            Sigla = "RH"
                        },
                        new
                        {
                            DeptoId = 3,
                            Nome = "Logistica",
                            Sigla = "LOG"
                        });
                });

            modelBuilder.Entity("Enterprise.Domain.Funcionario", b =>
                {
                    b.Property<int>("FuncionarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeptoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rg")
                        .HasColumnType("TEXT");

                    b.HasKey("FuncionarioId");

                    b.HasIndex("DeptoId");

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            FuncionarioId = 1,
                            DeptoId = 1,
                            FotoUrl = "idfjidjf",
                            Nome = "Marta Souza",
                            Rg = "87878787"
                        },
                        new
                        {
                            FuncionarioId = 2,
                            DeptoId = 2,
                            FotoUrl = "idfjidjf",
                            Nome = "Leticia Muriel",
                            Rg = "87878787"
                        },
                        new
                        {
                            FuncionarioId = 3,
                            DeptoId = 3,
                            FotoUrl = "idfjidjf",
                            Nome = "Renato Silva",
                            Rg = "87878787"
                        },
                        new
                        {
                            FuncionarioId = 4,
                            DeptoId = 3,
                            FotoUrl = "idfjidjf",
                            Nome = "Noel Lucas Souza",
                            Rg = "87878787"
                        },
                        new
                        {
                            FuncionarioId = 5,
                            DeptoId = 3,
                            FotoUrl = "idfjidjf",
                            Nome = "Manoel Barbosa",
                            Rg = "87878787"
                        },
                        new
                        {
                            FuncionarioId = 6,
                            DeptoId = 1,
                            FotoUrl = "idfjidjf",
                            Nome = "João Cardoso",
                            Rg = "87878787"
                        });
                });

            modelBuilder.Entity("Enterprise.Domain.Funcionario", b =>
                {
                    b.HasOne("Enterprise.Domain.Depto", "Depto")
                        .WithMany("Funcionarios")
                        .HasForeignKey("DeptoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Depto");
                });

            modelBuilder.Entity("Enterprise.Domain.Depto", b =>
                {
                    b.Navigation("Funcionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
